<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS4w53bi\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS4w53bi/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS4w53bi.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS4w53bi\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerS4w53bi\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'S4w53bi',
    'container.build_id' => '4045a67e',
    'container.build_time' => 1581364347,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS4w53bi');
