<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6jeiOyg\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6jeiOyg/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6jeiOyg.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6jeiOyg\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container6jeiOyg\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '6jeiOyg',
    'container.build_id' => '22bc341a',
    'container.build_time' => 1582387747,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6jeiOyg');
